---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy java-maven  app 
      community.kubernetes.k8s:
        src: java-maven.yaml
        state: present
       
