---
- name: Deploy app in new namespace
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /var/jenkins_home/workspace/Terraform-linode/Terraform/lke-cluster-config.yaml
    - name: Deploy java-maven  app 
      kubernetes.core.k8s:
        src: java-maven.yaml
        state: present
        kubeconfig: /var/jenkins_home/workspace/Terraform-linode/Terraform/lke-cluster-config.yaml
